# Site settings
title: helloworldchao
url: "http://helloworldchao.github.io"
baseurl: ""
description: > 
    helloworldchao的个人博客

# Your information
email: helloworldchao@outlook.com
author: helloworldchao
avatar: "//github.com/helloworldchao/helloworldchao.github.io/blob/master/img/profile_pic.jpg"
profile: Android开发者/Google粉
weibo_username: dragonyc
github_username:  helloworldchao

#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
