# Site settings
title: helloworldchao的博客
url: "http://helloworldchao.github.io"
baseurl: ""
description: > 
    helloworldchao的博客

# Your information
email: helloworldchao@outlook.com
author: Yu Chao
avatar: "/img/profile_pic.jpg"
profile: 一个什么都可以试一试的开发者
github_username:  helloworldchao

#来必力评论系统不注释即激活
livere: false

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: Asia/Shanghai
